name: heart Disease Prediction
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: action/checkout
      - uses: iterative/setup-cml@v1
      - name: train model
        - name: Train model
          run: |
            # Your ML workflow goes here
            pip install -r requirements.txt
            python train.py
        - name: Write CML report
          env:
            REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            # Post reports as comments in GitHub PRs
            echo "## Model Metrics" > reports.md
            cat metrics.txt >> report.md
            cml-send-comment report.md
